name: Auto Backport Label

on:
  workflow_call:
    inputs:
      pr_number:
        required: true
        type: number
      repo:
        required: true
        type: string

jobs:
  add-backport-label:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Fetch all release branches and PR labels
        id: fetch_info
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          REPO: ${{ inputs.repo }}
          PR_NUMBER: ${{ inputs.pr_number }}
        run: |
          set -euo pipefail

          branches=$(gh api repos/$REPO/branches --paginate --jq '.[].name')
          release_branches=$(echo "$branches" | grep -E '^release-harvester-v[0-9]+\.[0-9]+$' || true)

          if [[ -z "$release_branches" ]]; then
            echo "No release branches found."
            echo "should_label=false" >> $GITHUB_OUTPUT
            exit 0
          fi

          latest_branch=$(echo "$release_branches" | sort -Vr | head -n1)
          echo "latest_branch=$latest_branch" >> $GITHUB_OUTPUT

          version=$(echo "$latest_branch" | sed -E 's/^release-harvester-v//')
          version_with_patch="${version}.0"
          echo "Checking for tag: v${version_with_patch}"

          tags=$(gh api repos/$REPO/releases --paginate --jq '.[].tag_name')
          exact_match=$(echo "$tags" | grep -Fx "v${version_with_patch}" || true)

          if [[ -n "$exact_match" ]]; then
            echo "Release tag v${version_with_patch} exists; skipping label."
            echo "should_label=false" >> $GITHUB_OUTPUT
          else
            echo "Release tag v${version_with_patch} NOT found; will add backport label."
            echo "should_label=true" >> $GITHUB_OUTPUT
            echo "backport_label=require backport/v${version}" >> $GITHUB_OUTPUT
          fi

          pr_labels=$(gh pr view "$PR_NUMBER" --repo "$REPO" --json labels --jq '.labels[].name' || echo "")
          echo "pr_labels=$pr_labels" >> $GITHUB_OUTPUT

      - name: Add backport label if needed
        if: steps.fetch_info.outputs.should_label == 'true' && !contains(steps.fetch_info.outputs.pr_labels, steps.fetch_info.outputs.backport_label)
        uses: actions-ecosystem/action-add-labels@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          labels: ${{ steps.fetch_info.outputs.backport_label }}
