name: Build and Release Extension Charts

on:
  workflow_dispatch:
  release:
    types: [released]

defaults:
  run:
    shell: bash
    working-directory: ./

jobs:
  clear-yarn-cache:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Clear Yarn cache
        run: |
          yarn cache clean

  build-extension-charts:
    needs: clear-yarn-cache 
    uses: rancher/dashboard/.github/workflows/build-extension-charts.yml@master
    with:
      target_branch: gh-pages
      tagged_release: ${{ github.ref_name }}
    permissions:
      actions: write
      contents: write
      deployments: write
      pages: write

