name: Build and Release Extension Charts on PR Merge

on:
  pull_request:
    branches:
      - 'release-harvester-v*'
    types:
      - merged

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run linting
        uses: ./.github/actions/lint

  setup-target-branch:
    runs-on: ubuntu-latest
    outputs:
      target_branch: ${{ steps.get-version.outputs.target_branch }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Determine target branch
        id: get-version
        run: |
          if [[ "${{ github.ref_name }}" =~ ^release-harvester-v([0-9]+\.[0-9]+)$ ]]; then
            TARGET_BRANCH="v${BASH_REMATCH[1]}-head"
            echo "target_branch=${TARGET_BRANCH}" | tee -a "$GITHUB_ENV" "$GITHUB_OUTPUT"
          else
            echo "Error: invalid branch format." && exit 1
          fi

      - name: Ensure target branch exists
        run: |
          git fetch --all
          if ! git ls-remote --exit-code --heads origin "${{ env.target_branch }}"; then
            git checkout -b "${{ env.target_branch }}"
            git push origin "${{ env.target_branch }}"
          fi

  build-extension-charts:
    needs: setup-target-branch
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup environment
        run: |
          corepack enable
          yarn install --frozen-lockfile

      - name: Setup Helm
        uses: azure/setup-helm@v3
        with:
          version: v3.8.0

      - name: Build Helm charts
        run: yarn publish-pkgs -s ${{ github.repository }} -b ${{ needs.setup-target-branch.outputs.target_branch }}

      - name: Upload charts artifact
        uses: actions/upload-artifact@v4
        with:
          name: charts
          path: tmp

  release:
    needs:
      - setup-target-branch
      - build-extension-charts
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout release branch
        uses: actions/checkout@v4
        with:
          ref: '${{ github.ref_name }}'

      - name: Extract version from package.json
        id: get_version
        run: |
          VERSION=$(jq -r '.version' pkg/harvester/package.json)
          echo "VERSION=${VERSION}" | tee -a "$GITHUB_ENV"

      - name: Get last commit hash
        id: last_commit
        run: |
          LAST_COMMIT=$(git rev-parse HEAD)
          echo "LAST_COMMIT=${LAST_COMMIT}" | tee -a "$GITHUB_ENV"

      - name: Checkout target branch
        uses: actions/checkout@v4
        with:
          ref: '${{ needs.setup-target-branch.outputs.target_branch }}'

      - name: Remove old artifacts
        run: |
          rm -rf extensions/harvester/${{ env.VERSION }}
          rm -rf charts/harvester/${{ env.VERSION }}
          rm -f assets/harvester/harvester-${{ env.VERSION }}.tgz

      - name: Configure Git
        run: |
          git config user.name 'github-actions[bot]'
          git config user.email 'github-actions[bot]@users.noreply.github.com'

      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: charts

      - name: Commit and push artifacts
        run: |
          git add ./{assets,charts,extensions,index.yaml}
          git commit -m "CI Build Artifacts (Commit: ${{ env.LAST_COMMIT }}, Version: ${{ env.VERSION }})"
          git push origin ${{ needs.setup-target-branch.outputs.target_branch }}

      - name: Run Helm chart releaser
        uses: helm/chart-releaser-action@v1.4.1
        with:
          charts_dir: ./charts
        env:
          CR_TOKEN: '${{ secrets.GITHUB_TOKEN }}'
          CR_SKIP_EXISTING: true