name: Build Standalone on Release
on:
  push:
    tags:
      - v[1-9].*

jobs:
  build:
    name: Build and Upload Package
    uses: ./.github/workflows/build-and-publish-standalone.yaml
    permissions:
      contents: read
      packages: write
      id-token: write
    with:
      CI_BUILD_TAG: ${{github.ref_name}}
