name: Build and Release Extension Charts

on:
  workflow_dispatch:
  release:
    types: [released]

defaults:
  run:
    shell: bash
    working-directory: ./

jobs:
  clean-cache:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: check if yarn.lock or package.json changed
        id: check-changes
        run: |
          git diff --exit-code --quiet yarn.lock || echo "yarn.lock has changed"
          git diff --exit-code --quiet package.json || echo "package.json has changed"

      - name: clean yarn cache
        if: steps.check-changes.outputs.changed == 'true'
        run: |
          yarn cache clean
          rm -rf ~/.yarn/cache

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Run tests
        uses: ./.github/actions/lint

  build-extension-charts:
    needs:
      - lint
      - clean-cache
    uses: rancher/dashboard/.github/workflows/build-extension-charts.yml@master
    permissions:
      actions: write
      contents: write
      deployments: write
      pages: write
    with:
      target_branch: gh-pages
      tagged_release: ${{ github.ref_name }}
