name: Build and Push Extension Charts on PR Merge

on:
  push:
    branches:
      - 'release-harvester-v*'
  pull_request:
    branches:
      - 'release-harvester-v*'
    types:
      - merged

defaults:
  run:
    shell: bash
    working-directory: ./

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Run tests
        uses: ./.github/actions/lint